### ISSUE TITLE
Dependency on ng-Cordova

### ISSUE THREAD

**Issue by sherifdarwish** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#10]
Hi,
First i would like to thank you for your efforts in creating such a nice reusable interface with drupal based on Angular and sharing the ionic sample

I see an issue with the dependency on ng-cordova and i think it should be changed to ngCordova in articleFeed.controller.js

This is what i did for the demo to work on my side

Thnaks

**Comment by BioPhoton** [comment]
Hi @sherifdarwish,
thanks!

I updated the whole project and its dependencies. 
Shoul work now out of the box. Just follow the new readme.

If something don't work feel free to reopen this issue. :-)

By the way. If you are interested to see full featureset in action visite  [ng-drupal-7-services-explorer](http://www.drupalionic.org/explore/)
