### ISSUE TITLE
Infinite loop in token if not able to get token in connect

### ISSUE THREAD

**Issue by sherifdarwish** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#11]
Hi,

Thanks again for your efforts in supporting this angular-ionic-drupal combination, 

I am trying to familiarize myself with your code and the way it is written and i can see one bug that is happening when the app is not able to connect to drupal to get the connect token, in such scenario the locationChangeStartCallback is called all over again and again

i am not 100% familiar with the $q,promise,.. thing so not able to suggest a fix now, but i am still trying 

You can test this on emulator or browser if you disconnect from internet and tried to run the application

Regards,
Sherif

**Comment by BioPhoton** [comment]
Hi, could you please post this issue to https://github.com/BioPhoton/ng-drupal-7-services.
Because this error depends to this lib and not the ionic demo. 

I close the issue here and will try to fix it soon!

**Comment by BioPhoton** [comment]
I opened a issue for that hrer => [ng-drupal-7-services/issues/12](https://github.com/BioPhoton/ng-drupal-7-services/issues/12)
