### ISSUE TITLE
validation error messages always appear on on form submit 

### ISSUE THREAD

**Issue by sherifdarwish** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#12]
Below validation error message always fire on form submit even if the input fields were correctly populated, this is happening as the <ng-messages will always show if the form is being submitted regardless of $invalid status of form controls

I see this happening in register.view.html 
<ng-messages class="form-errors"
                     ng-if="registerForm.name.$invalid && registerForm.name.$touched || registerForm.$submitted"
                     for="registerForm.name.$error">
        </ng-messages>

**Comment by BioPhoton** [comment]
Fixed in master and Tag 0.3.1.

Implemented ngMesssages and errors for client and server validation.
