### ISSUE TITLE
hello,How output article

### ISSUE THREAD

**Issue by patrickpeng2091** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#13]
http://dev-ionic-demo.pantheon.io/api/v1/views/testview?page=0&pagesize=25&format_output=0

my views path
http://1035.dd:8084/api/v1/views/testview?page=0&pagesize=25&format_output=0

![image](https://cloud.githubusercontent.com/assets/4326820/13379903/89343ac4-de6e-11e5-8b3e-46c2cd2a39d7.png)

200 success

How to add field on the views ?

**Comment by patrickpeng2091** [comment]
https://github.com/BioPhoton/ng-drupal-7-services-explorer/tree/master/resources/drupal  

thanks

**Comment by patrickpeng2091** [comment]
but ,
![image](https://cloud.githubusercontent.com/assets/4326820/13384451/99a44a36-ded0-11e5-8c83-2e9302c6c9c3.png)

```
function getPathToImgByStyle(style, isPrivate) {
            return  getDrupalPath() + 'sites/default/files/styles/'+style+'/'+ ( (isPrivate)?DrupalApiConstant.privateFilePath:DrupalApiConstant.publicFilePath );

        }
```

how fix this ?

**Comment by BioPhoton** [comment]
Hi patrick-peng,

Thx for the effort you put into by creating this issue!

I'm not shure if i understand right. I see first you looked for the virews setup and how to add custom fields to your view. You found my views export and i guess imported it properly into your drupal setup.

The other thin is that you path to the image is not correct. Am i right?
If yes, please try to provide a bit more code or describe you problem better.

I meantime i will update docs for this demo and also add drupal contenttype and views exports.

**Comment by patrickpeng2091** [comment]
hi, @BioPhoton 
How do I configure the path of the image ？

**Comment by BioPhoton** [comment]
i beleve your code looks something like this:  

```
var pathToImage = getPathToImgByStyle();
```

and should look like this:  

```
var pathToImage = getPathToImgByStyle('medium');
```

Am i right?

**Comment by BioPhoton** [comment]
By the way, you will find exports for view, contnettype and permissions in the [drupal folder](https://github.com/BioPhoton/Ionic-Angular-Headless-Drupal-Demo/tree/master/drupal)

**Comment by patrickpeng2091** [comment]
The characters are not the same。
https://github.com/BioPhoton/Ionic-Angular-Headless-Drupal-Demo/blob/master/drupal/permissions_export.txt

https://github.com/BioPhoton/ng-drupal-7-services-explorer/blob/master/resources/drupal/testview_export.txt

![image](https://cloud.githubusercontent.com/assets/4326820/13413890/ec9485a4-df88-11e5-9e25-030b408d3435.png)

![image](https://cloud.githubusercontent.com/assets/4326820/13413810/790cd9d8-df88-11e5-9e65-753df962f6c9.png)

**Comment by BioPhoton** [comment]
should work now

**Comment by patrickpeng2091** [comment]
thank you

**Comment by BioPhoton** [comment]
:-)

**Comment by patrickpeng2091** [comment]
article_view_export.txt    and  articlefeed_view_export.txt    Two the same?

**Comment by BioPhoton** [comment]
deleted the other one
