### ISSUE TITLE
Paid help needed on hybrid mobile app using Ionic framework and Drupal 7 as the backend

### ISSUE THREAD

**Issue by click2tman** [BioPhoton/Ionic-Angular-Headless-Drupal-Demo#15]
I am working on an hybrid mobile app using Ionic framework and Drupal 7 as the backend. I need someone with the skills to work with other developers to finish the app quickly. The Drupal backend is based on Drupal Services Module. The key components remaining are; Sign In and Sign Up using Drupal, Sign In and Sign Up using Social Connect (Facebook, twitter, Google), Write a comment/review, edit a business/node, add a business/node. The app is a business directory app. You can contact me via skype using click2tman and via email using tamba@tambalamin.me

**Comment by BioPhoton** [comment]
I close this issue because contact already happened.
